SELECT
    COUNT(JOB_ID)                       AS JOB_POSTED_COUNT,
    EXTRACT(MONTH FROM JOB_POSTED_DATE) AS MONTH
FROM
    JOB_POSTINGS_FACT
WHERE
    JOB_TITLE_SHORT = 'Data Analyst'
GROUP BY
    MONTH
ORDER BY
    JOB_POSTED_COUNT DESC;